### ISSUE TITLE
Nitpick: AD8541 used as overtemperature comparators

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/Stabilizer_Piezo_Driver#6]
Just scrolled through the release PDF out of curiosity, and noticed that 2xAD8541 are used as comparators/LED drivers for the overtemperature circuit. Since those aren't appear anywhere else on the BOM, isn't that a bit of overkill, i.e. wouldn't pretty much any cheap dual comparator for 1/10th the price also do the trick?

**Comment by gkasprow** [comment]
I wrote the same in of of my reviews

**Comment by JakubKajzer** [comment]
AD8541 changed to LM358

**Comment by dnadlinger** [comment]
(Haven't reviewed the changes myself, but then again, it's not my role to do so. :) )
